# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /secondary/assad/Linux_Unreal_Engine_5.8.2

TARGETS = \
	UEIntro_Dev_26-Android-DebugGame  \
	UEIntro_Dev_26-Android-Development  \
	UEIntro_Dev_26-Android-Shipping  \
	UEIntro_Dev_26-Linux-DebugGame  \
	UEIntro_Dev_26-Linux-Development  \
	UEIntro_Dev_26-Linux-Shipping  \
	UEIntro_Dev_26-LinuxArm64-DebugGame  \
	UEIntro_Dev_26-LinuxArm64-Development  \
	UEIntro_Dev_26-LinuxArm64-Shipping  \
	UEIntro_Dev_26 \
	UEIntro_Dev_26Editor-Linux-DebugGame  \
	UEIntro_Dev_26Editor-Linux-Development  \
	UEIntro_Dev_26Editor \
	ChaosTestHarness \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend UEIntro_Dev_26Editor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug UEIntro_Dev_26Editor-Linux-Debug


UEIntro_Dev_26-Android-DebugGame:
	 $(BUILD) UEIntro_Dev_26 Android DebugGame  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26-Android-Development:
	 $(BUILD) UEIntro_Dev_26 Android Development  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26-Android-Shipping:
	 $(BUILD) UEIntro_Dev_26 Android Shipping  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26-Linux-DebugGame:
	 $(BUILD) UEIntro_Dev_26 Linux DebugGame  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26-Linux-Development:
	 $(BUILD) UEIntro_Dev_26 Linux Development  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26-Linux-Shipping:
	 $(BUILD) UEIntro_Dev_26 Linux Shipping  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26-LinuxArm64-DebugGame:
	 $(BUILD) UEIntro_Dev_26 LinuxArm64 DebugGame  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26-LinuxArm64-Development:
	 $(BUILD) UEIntro_Dev_26 LinuxArm64 Development  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26-LinuxArm64-Shipping:
	 $(BUILD) UEIntro_Dev_26 LinuxArm64 Shipping  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26: UEIntro_Dev_26-Linux-Development

UEIntro_Dev_26Editor-Linux-DebugGame:
	 $(BUILD) UEIntro_Dev_26Editor Linux DebugGame  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26Editor-Linux-Development:
	 $(BUILD) UEIntro_Dev_26Editor Linux Development  -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" $(ARGS)

UEIntro_Dev_26Editor: UEIntro_Dev_26Editor-Linux-Development

ChaosTestHarness: ChaosTestHarness-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/assad/Development/UEIntro_Dev_26/UEIntro_Dev_26.uproject" -Game 

.PHONY: $(TARGETS)
